# Netlify build configuration
[build]
  publish = "."   # serve the current directory (where index.html lives)

# Local dev (if you run `netlify dev`)
[dev]
  command = ""    # no build step, just static
  port = 8888

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
